import type { Course } from "./courses-model"

export function buildMockCourses(): Course[] {
  return [
    {
      id: "course-react-patterns",
      title: "Advanced React Patterns",
      instructor: "Kent C. Dodds",
      courseLink: "https://example.com/react-patterns",
      links: [
        "https://react.dev/learn",
        "https://beta.reactjs.org/learn/thinking-in-react",
      ],
      topics: ["react", "patterns", "hooks", "composition"],
      progress: 62,
      createdAt: "2026-01-08T10:15:00Z",
      updatedAt: "2026-03-09T16:00:00Z",
    },
    {
      id: "course-postgres-perf",
      title: "Postgres Performance",
      instructor: "Supabase",
      courseLink: null,
      links: ["https://www.postgresql.org/docs/current/"],
      topics: ["postgres", "indexes", "query-plans"],
      progress: 24,
      createdAt: "2026-02-02T09:30:00Z",
      updatedAt: "2026-03-06T12:00:00Z",
    },
    {
      id: "course-nextjs",
      title: "Next.js App Router Deep Dive",
      instructor: "Vercel",
      courseLink: "https://example.com/nextjs",
      links: [],
      topics: ["nextjs", "react", "routing"],
      progress: 48,
      createdAt: "2026-01-18T18:45:00Z",
      updatedAt: "2026-03-10T11:25:00Z",
    },
    {
      id: "course-typescript",
      title: "TypeScript Advanced Types",
      instructor: "Matt Pocock",
      courseLink: "https://example.com/typescript",
      links: ["https://www.typescriptlang.org/docs/"],
      topics: ["typescript", "generics", "types"],
      progress: 73,
      createdAt: "2025-12-12T08:00:00Z",
      updatedAt: "2026-02-28T14:20:00Z",
    },
    {
      id: "course-system-design",
      title: "System Design for Developers",
      instructor: null,
      courseLink: null,
      links: [],
      topics: ["system-design", "scaling"],
      progress: 10,
      createdAt: "2026-03-01T09:15:00Z",
      updatedAt: "2026-03-02T09:15:00Z",
    },
    {
      id: "course-css",
      title: "Modern CSS Layouts",
      instructor: "Josh W Comeau",
      courseLink: "https://example.com/css",
      links: ["https://developer.mozilla.org/en-US/docs/Web/CSS"],
      topics: ["css", "layout", "tailwind"],
      progress: 35,
      createdAt: "2026-02-20T15:05:00Z",
      updatedAt: "2026-03-08T10:10:00Z",
    },
    {
      id: "course-testing",
      title: "Testing React Applications",
      instructor: "Cypress",
      courseLink: null,
      links: ["https://testing-library.com/", "https://playwright.dev/"],
      topics: ["testing", "react", "playwright"],
      progress: 55,
      createdAt: "2026-01-28T12:00:00Z",
      updatedAt: "2026-03-07T09:00:00Z",
    },
  ]
}
