import type { ReviewCourse, ReviewNote, ReviewSession } from "./review-model"

export const REVIEW_MOCK_COURSES: ReviewCourse[] = [
  { id: "course_react", title: "Advanced React Patterns" },
  { id: "course_sql", title: "Postgres Performance" },
  { id: "course_ts", title: "TypeScript Deep Dive" },
]

export const REVIEW_MOCK_NOTES_POOL: ReviewNote[] = [
  {
    id: "note_1",
    type: "qa",
    courseId: "course_react",
    courseTitle: "Advanced React Patterns",
    question: "What problem does useEffect dependency array solve?",
    answer:
      "It controls when the effect re-runs by specifying which reactive values should trigger the effect. It prevents stale closures and unnecessary re-execution.",
    understandingLevel: 2,
    flag: true,
  },
  {
    id: "note_2",
    type: "qa",
    courseId: "course_react",
    courseTitle: "Advanced React Patterns",
    question: "When should you use useMemo?",
    answer:
      "Use it to memoize expensive computations between renders when the inputs are stable. It is not a general performance fix.",
    understandingLevel: 2,
    flag: false,
  },
  {
    id: "note_3",
    type: "qa",
    courseId: "course_sql",
    courseTitle: "Postgres Performance",
    question: "What is a partial index and why use it?",
    answer:
      "A partial index indexes only rows that match a WHERE predicate. It keeps indexes smaller and faster for hot subsets of data.",
    understandingLevel: 3,
    flag: true,
  },
  {
    id: "note_4",
    type: "qa",
    courseId: "course_ts",
    courseTitle: "TypeScript Deep Dive",
    question: "Why prefer unknown over any?",
    answer:
      "unknown forces you to narrow before use, preserving type safety. any disables type checking and can hide errors.",
    understandingLevel: 1,
    flag: false,
  },
  {
    id: "note_5",
    type: "qa",
    courseId: null,
    courseTitle: null,
    question: "What is a discriminated union?",
    answer:
      "A union of object types that share a common literal field (the discriminator). It enables exhaustive checking and safer control flow.",
    understandingLevel: 2,
    flag: false,
  },
  {
    id: "note_6",
    type: "qa",
    courseId: "course_sql",
    courseTitle: "Postgres Performance",
    question: "Why should you avoid SELECT * in production?",
    answer:
      "It fetches unnecessary columns, can break when schemas change, and can prevent index-only scans. Name columns explicitly.",
    understandingLevel: 2,
    flag: true,
  },
]

export const REVIEW_MOCK_SESSIONS: ReviewSession[] = [
  {
    id: "session_1",
    userId: "user_1",
    name: "React Hooks Warmup",
    date: "2026-03-10",
    questionCount: 10,
    shuffled: true,
    flaggedOnly: false,
    accuracy: 80,
    timeSpentMinutes: 17,
    notesLeveledUp: ["note_1"],
    notesLeveledDown: ["note_4"],
    weakestCourseId: "course_ts",
    strongestCourseId: "course_sql",
    createdAt: "2026-03-10T12:20:00Z",
  },
  {
    id: "session_2",
    userId: "user_1",
    name: "SQL Index Review",
    date: "2026-03-08",
    questionCount: 20,
    shuffled: false,
    flaggedOnly: true,
    accuracy: 65,
    timeSpentMinutes: 24,
    notesLeveledUp: ["note_3"],
    notesLeveledDown: [],
    weakestCourseId: "course_react",
    strongestCourseId: "course_sql",
    createdAt: "2026-03-08T10:12:00Z",
  },
  {
    id: "session_3",
    userId: "user_1",
    name: "TypeScript Narrowing",
    date: "2026-03-05",
    questionCount: 10,
    shuffled: false,
    flaggedOnly: false,
    accuracy: 90,
    timeSpentMinutes: 12,
    notesLeveledUp: ["note_4"],
    notesLeveledDown: [],
    weakestCourseId: null,
    strongestCourseId: "course_ts",
    createdAt: "2026-03-05T18:03:00Z",
  },
  {
    id: "session_4",
    userId: "user_1",
    name: "Mixed Practice",
    date: "2026-02-27",
    questionCount: 20,
    shuffled: true,
    flaggedOnly: false,
    accuracy: 55,
    timeSpentMinutes: 31,
    notesLeveledUp: [],
    notesLeveledDown: ["note_2"],
    weakestCourseId: "course_react",
    strongestCourseId: null,
    createdAt: "2026-02-27T09:41:00Z",
  },
  {
    id: "session_5",
    userId: "user_1",
    name: "Flagged Notes Only",
    date: "2026-02-20",
    questionCount: 10,
    shuffled: true,
    flaggedOnly: true,
    accuracy: 70,
    timeSpentMinutes: 19,
    notesLeveledUp: ["note_6"],
    notesLeveledDown: ["note_1"],
    weakestCourseId: "course_react",
    strongestCourseId: "course_sql",
    createdAt: "2026-02-20T14:09:00Z",
  },
  {
    id: "session_6",
    userId: "user_1",
    name: "Uncategorized Focus",
    date: "2026-02-14",
    questionCount: 10,
    shuffled: false,
    flaggedOnly: false,
    accuracy: 60,
    timeSpentMinutes: 9,
    notesLeveledUp: [],
    notesLeveledDown: [],
    weakestCourseId: null,
    strongestCourseId: null,
    createdAt: "2026-02-14T08:10:00Z",
  },
]

export function getMockAvailableQaNotes({ flaggedOnly }: { flaggedOnly: boolean }) {
  return REVIEW_MOCK_NOTES_POOL.filter((n) => (flaggedOnly ? n.flag : true))
}
