import type { Note } from "@/app/notes/ui/notes-model"

export const HOMEPAGE_MOCK_NOTES: Note[] = [
  {
    id: "hp-1",
    type: "qa",
    courseId: "react",
    courseTitle: "React",
    question: "What problem does useMemo solve?",
    answer:
      "useMemo memoizes a computed value so you don’t recompute it on every render. It helps when the computation is expensive or when referential equality matters for memoized children.",
    body: null,
    codeSnippet: null,
    codeLanguage: "tsx",
    understandingLevel: 2,
    flag: false,
    createdAt: "2026-03-02T10:00:00.000Z",
    updatedAt: "2026-03-10T12:00:00.000Z",
  },
  {
    id: "hp-2",
    type: "qa",
    courseId: "ts",
    courseTitle: "TypeScript",
    question: "How do discriminated unions enable exhaustive checks?",
    answer:
      "Use a shared literal field like `type` or `status`. When you switch on that field, TypeScript can narrow each branch and warn you if you forget a case.",
    body: null,
    codeSnippet:
      "type Result =\n  | { status: 'success'; data: string }\n  | { status: 'error'; error: string }\n\nfunction handle(r: Result) {\n  switch (r.status) {\n    case 'success':\n      return r.data\n    case 'error':\n      return r.error\n    default: {\n      const _exhaustive: never = r\n      return _exhaustive\n    }\n  }\n}",
    codeLanguage: "typescript",
    understandingLevel: 3,
    flag: true,
    createdAt: "2026-03-04T10:00:00.000Z",
    updatedAt: "2026-03-09T18:00:00.000Z",
  },
  {
    id: "hp-3",
    type: "qa",
    courseId: null,
    courseTitle: null,
    question: "What’s the difference between async/await and promises?",
    answer:
      "async/await is syntax on top of promises. It lets you write promise-based code that reads like synchronous code, but it still returns promises and schedules work asynchronously.",
    body: null,
    codeSnippet: null,
    codeLanguage: "javascript",
    understandingLevel: 1,
    flag: false,
    createdAt: "2026-03-06T10:00:00.000Z",
    updatedAt: "2026-03-08T18:00:00.000Z",
  },
  {
    id: "hp-4",
    type: "freeform",
    courseId: "db",
    courseTitle: "Postgres",
    question: null,
    answer: null,
    body:
      "Chapter recap: Indexes speed up reads but add write overhead. Use composite indexes when filtering on multiple columns, and remember that Postgres doesn’t automatically index foreign keys.",
    codeSnippet: null,
    codeLanguage: "sql",
    understandingLevel: null,
    flag: false,
    createdAt: "2026-03-07T10:00:00.000Z",
    updatedAt: "2026-03-07T10:00:00.000Z",
  },
  {
    id: "hp-5",
    type: "freeform",
    courseId: "review",
    courseTitle: "Study",
    question: null,
    answer: null,
    body:
      "Review session notes: The goal isn’t perfect recall — it’s consistent retrieval practice. Rate honestly, then let the session guide what you revisit next.",
    codeSnippet: null,
    codeLanguage: "markdown",
    understandingLevel: null,
    flag: true,
    createdAt: "2026-03-08T10:00:00.000Z",
    updatedAt: "2026-03-10T10:00:00.000Z",
  },
]
