export const refs = {
  loadingSection: document.getElementById("loading-section"),
  authSection: document.getElementById("auth-section"),
  appSection: document.getElementById("app-section"),
  errorSection: document.getElementById("error-section"),
  errorMessage: document.getElementById("error-message"),
  loginButton: document.getElementById("login-button"),
  greeting: document.getElementById("greeting"),
  syncStatus: document.getElementById("sync-status"),
  todayLabel: document.getElementById("today-label"),
  todayTime: document.getElementById("today-time"),
  todayMood: document.getElementById("today-mood"),
  todayNote: document.getElementById("today-note"),
  tabButtons: [
    document.getElementById("tab-capture"),
    document.getElementById("tab-timer"),
    document.getElementById("tab-log"),
  ],
  tabPanels: {
    capture: document.getElementById("panel-capture"),
    timer: document.getElementById("panel-timer"),
    log: document.getElementById("panel-log"),
  },
  noteSaveStatus: document.getElementById("note-save-status"),
  noteTypeQa: document.getElementById("note-type-qa"),
  noteTypeFreeform: document.getElementById("note-type-freeform"),
  noteQuestionInput: document.getElementById("note-question-input"),
  noteAnswerInput: document.getElementById("note-answer-input"),
  noteBodyInput: document.getElementById("note-body-input"),
  noteSave: document.getElementById("note-save"),
  qaFields: document.getElementById("qa-fields"),
  freeformFields: document.getElementById("freeform-fields"),
  courseDisclosure: document.getElementById("course-disclosure"),
  courseDisclosureIcon: document.getElementById("course-disclosure-icon"),
  coursePanel: document.getElementById("course-panel"),
  courseSaveStatus: document.getElementById("course-save-status"),
  courseTitleInput: document.getElementById("course-title-input"),
  courseInstructorInput: document.getElementById("course-instructor-input"),
  courseLinkInput: document.getElementById("course-link-input"),
  courseSave: document.getElementById("course-save"),
  dailyLogStatus: document.getElementById("daily-log-status"),
  logHours: document.getElementById("log-hours"),
  logMinutes: document.getElementById("log-minutes"),
  dailyNoteInput: document.getElementById("daily-note-input"),
  dailyLogSave: document.getElementById("daily-log-save"),
  timerValue: document.getElementById("timer-value"),
  timerStatus: document.getElementById("timer-status"),
  timerStart: document.getElementById("timer-start"),
  timerPause: document.getElementById("timer-pause"),
  timerResume: document.getElementById("timer-resume"),
  timerStop: document.getElementById("timer-stop"),
  timerReset: document.getElementById("timer-reset"),
  timerSavePanel: document.getElementById("timer-save-panel"),
  timerNoteInput: document.getElementById("timer-note-input"),
  timerSave: document.getElementById("timer-save"),
  timerSaveHint: document.getElementById("timer-save-hint"),
  dashboardLink: document.getElementById("dashboard-link"),
  settingsToggle: document.getElementById("settings-toggle"),
  settingsPanel: document.getElementById("settings-panel"),
  settingsStatus: document.getElementById("settings-status"),
  settingsHint: document.getElementById("settings-hint"),
  siteEnvButtons: Array.from(document.querySelectorAll("[data-site-base-url]")),
}

export const selectRefs = {
  noteCourse: {
    root: document.getElementById("select-note-course"),
    trigger: document.getElementById("select-note-course-trigger"),
    label: document.getElementById("select-note-course-label"),
    panel: document.getElementById("select-note-course-panel"),
    list: document.getElementById("select-note-course-list"),
  },
  noteUnderstanding: {
    root: document.getElementById("select-note-understanding"),
    trigger: document.getElementById("select-note-understanding-trigger"),
    label: document.getElementById("select-note-understanding-label"),
    panel: document.getElementById("select-note-understanding-panel"),
    list: document.getElementById("select-note-understanding-list"),
  },
  dailyMood: {
    root: document.getElementById("select-daily-mood"),
    trigger: document.getElementById("select-daily-mood-trigger"),
    label: document.getElementById("select-daily-mood-label"),
    panel: document.getElementById("select-daily-mood-panel"),
    list: document.getElementById("select-daily-mood-list"),
  },
  timerMood: {
    root: document.getElementById("select-timer-mood"),
    trigger: document.getElementById("select-timer-mood-trigger"),
    label: document.getElementById("select-timer-mood-label"),
    panel: document.getElementById("select-timer-mood-panel"),
    list: document.getElementById("select-timer-mood-list"),
  },
}
